name: ha-file-viewer
version: 0.1.0.0
license: MIT
author: "KentuLiveAccount"
extra-source-files: []

library:
  exposed-modules: 
    - HaFileViewer.Backend.BidirectionalScanner
    - HaFileViewer.Backend.LineCache
    - HaFileViewer.Backend.Types
    - HaFileViewer.Backend.SparseIndex
    - HaFileViewer.CUILogViewer.ViewState
    - HaFileViewer.CUILogViewer.Operations
  other-modules: []  # Don't auto-discover
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - base >= 4.9 && < 5
    - bytestring
    - text
    - vector
    - mmap
    - containers
    - time
    - directory
    - brick >= 2.0
    - vty
    

executables:
  cui-log-viewer:
    main: Main.hs
    source-dirs: src/HaFileViewer/CUILogViewer
    other-modules: []  # Only Main.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - ha-file-viewer
      - base
      - text
      - brick >= 2.0
      - vty
      - directory
      - microlens

tests:
  ui-systematic-test:
    main: Systematic.hs
    source-dirs: src/HaFileViewer/CUILogViewer/Test
    other-modules: []  # Only Systematic.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-N -Wall
    dependencies:
      - ha-file-viewer
      - base
      - text
      - directory
      - brick >= 2.0
      - vty

  bidirectional-scanner-test:
    main: BidirectionalScanner.hs
    source-dirs: src/HaFileViewer/Backend/Test
    other-modules: []
    ghc-options: -threaded -rtsopts -with-rtsopts=-N -Wall
    dependencies:
      - ha-file-viewer
      - base
      - hspec
      - temporary
      - filepath
      - text
      - bytestring
      - mmap

  linecache-test:
    main: LineCache.hs
    source-dirs: src/HaFileViewer/Backend/Test
    other-modules: []
    ghc-options: -threaded -rtsopts -with-rtsopts=-N -Wall
    dependencies:
      - ha-file-viewer
      - base
      - hspec
      - temporary
      - text
      - bytestring


