name: ha-file-viewer
version: 0.1.0.0
license: MIT
author: "KentuLiveAccount"
extra-source-files: []

library:
  exposed-modules: 
    - HaFileViewer.LineMap
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - base >= 4.9 && < 5
    - bytestring
    - text
    - vector
    - mmap
    

executables:
  ha-file-viewer-cui:
    main: Main.hs
    source-dirs: app/cui
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - ha-file-viewer
      - base
      - text

  ha-file-viewer-web:
    main: Main.hs
    source-dirs: app/web
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - ha-file-viewer
      - base
      - text
      - directory
      - scotty
      - aeson
      - wai-extra
      - http-types

tests:
  ha-file-viewer-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -threaded -rtsopts -with-rtsopts=-N -Wall
    dependencies:
      - ha-file-viewer
      - base
      - hspec
      - temporary
      - filepath
      - directory
      - text
      - bytestring
      - time

